/**
 * One-click install bundles for agent harnesses.
 *
 * Every harness speaks "Agent Skills" (SKILL.md), but each expects the file
 * in a different directory of the user's project. A bundle is a small .zip
 * that mirrors the target layout, so installing is just "extract here".
 */

import { createZipBlob, downloadBlob } from "./zip";
import { serializeSkill, type Skill } from "./skills";

export interface Harness {
  id: string;
  label: string;
  vendor: string;
  /** Directory (relative to the project root) where skills live. */
  baseDir: string;
  fileName: string;
  installNote: string;
}

export const HARNESSES: Harness[] = [
  {
    id: "claude-code",
    label: "Claude Code",
    vendor: "Anthropic",
    baseDir: ".claude/skills",
    fileName: "SKILL.md",
    installNote:
      "Extract the zip into your project root for project skills, or into your home directory (~/.claude/skills) to make the skill available in every project.",
  },
  {
    id: "codex",
    label: "Codex",
    vendor: "OpenAI",
    baseDir: ".codex/skills",
    fileName: "SKILL.md",
    installNote:
      "Extract the zip into your project root. Codex discovers skills under .codex/skills/ automatically.",
  },
  {
    id: "cursor",
    label: "Cursor",
    vendor: "Cursor",
    baseDir: ".cursor/skills",
    fileName: "SKILL.md",
    installNote:
      "Extract the zip into your project root. Cursor loads Agent Skills from .cursor/skills/.",
  },
  {
    id: "copilot",
    label: "Copilot",
    vendor: "GitHub",
    baseDir: ".github/skills",
    fileName: "SKILL.md",
    installNote:
      "Extract the zip into your repository root. Copilot discovers Agent Skills under .github/skills/.",
  },
  {
    id: "gemini",
    label: "Gemini CLI",
    vendor: "Google",
    baseDir: ".gemini/skills",
    fileName: "SKILL.md",
    installNote:
      "Extract the zip into your project root. Gemini CLI loads skills from .gemini/skills/.",
  },
];

/** Path of the skill file inside the bundle, e.g. ".claude/skills/foo/SKILL.md". */
export function skillInstallPath(harness: Harness, skillName: string): string {
  return `${harness.baseDir}/${skillName}/${harness.fileName}`;
}

/** Build the install bundle: the skill at its harness path + an INSTALL.txt. */
export function buildInstallBundle(harness: Harness, skill: Skill): Blob {
  const skillPath = skillInstallPath(harness, skill.name);
  const installTxt = [
    `Install "${skill.name}" for ${harness.label}`,
    "=".repeat(40),
    "",
    "1. Extract this zip into your project root",
    `   (so that "${skillPath}" lands in place).`,
    "",
    `2. ${harness.installNote}`,
    "",
    `3. Restart / reload ${harness.label} so it picks up the new skill.`,
    "",
    `Skill: ${skill.name}`,
    `Description: ${skill.description}`,
    `Generated by Agent Skill Studio (local-first, nothing was uploaded).`,
    "",
  ].join("\n");

  return createZipBlob([
    { path: skillPath, content: serializeSkill(skill) },
    { path: "INSTALL.txt", content: installTxt },
  ]);
}

/** Build the bundle and trigger a browser download for it. */
export function downloadInstallBundle(harness: Harness, skill: Skill): void {
  const blob = buildInstallBundle(harness, skill);
  downloadBlob(`${skill.name}.${harness.id}.zip`, blob);
}
